[rewrite_local]
^https:\/\/api\.getmoshi\.app\/api\/v1\/licenses\/(?:me|activate|[^\/]+\/devices)(?:[\/?#]|$) url script-analyze-echo-response https://raw.githubusercontent.com/ouones/QuanxBackup/main/Rewrite%28Yu9191%29/moshi/moshi-pro.js

[mitm]
hostname = api.getmoshi.app
